# Site settings

project:
    name: "Package"
    alt_name: "Package"
    tagline: Description
    author: "CupOfTea696"
    github: "https://github.com/CupOfTea696/Package/"
    package: "cupoftea/package"
navigation:
  - name: Documentation
    url: "docs"
    navigation:
      - name: Getting Started
        type: category
      - name: Installation
        type: page
        url: "installation"
  - name: API
    url: "docs/api"
url: "http://package.cupoftea.io"
twitter_username: CupOfTea696
github_username:  CupOfTea696

# Build settings
exclude: ['build.sh']
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'with_toc_data', 'html_toc', 'strikethrough', 'autolink', 'tables', 'footnotes', 'underline']
highlighter: pygments
pygments_options: ['startinline']
gems: [jekyll-assets, nokogiri, octopress-minify-html, redcarpet, pygments.rb]
assets:
  compress:
    css: true
    js: true
  prefix: "assets"
  assets:
    - "app.css"
    - "app.js"
  digest: false
  sources:
    - _assets
